[sources.kafka.credentials]
bootstrap_servers = "bootstrap_servers"  # Please set me up!
group_id = "group_id"  # Please set me up!
security_protocol = "security_protocol"  # Please set me up!
sasl_mechanisms = "sasl_mechanisms"  # Please set me up!
sasl_username = "sasl_username"  # Please set me up!
sasl_password = "sasl_password"  # Please set me up!

[destination.snowflake.credentials]
database = "database"  # Please set me up!
password = "password"  # Please set me up!
username = "username"  # Please set me up!
host = "host"  # Please set me up!
warehouse = "warehouse"  # Please set me up!
role = "role"  # Please set me up!
